# Generated by Django 3.2.3 on 2021-06-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppics', '0002_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
