# Generated by Django 3.2.3 on 2021-06-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppics', '0003_auto_20210601_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='image_location',
            new_name='location',
        ),
    ]
