# Generated by Django 3.2.3 on 2021-06-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppics', '0004_auto_20210603_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='apppics.category'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='apppics.location'),
        ),
    ]
