# Generated by Django 3.2.3 on 2021-06-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppics', '0005_auto_20210603_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, to='apppics.category'),
        ),
    ]
